language: cpp

os:
  - linux
  
compiler:
  - gcc 
  
env:
  global:
    - secure: Wt43koA55PGba7TsJ85f9vHyW4b/QfPh2Ywhw5+40sba5Us4Y3h+l23VyVjQbXuHfCGgC+t5+AABm1ubhL4MjCvxzS9BepjhNN92LPXoLfBRM2AHhNLWMKLLxt4T7OofjnLPw21l6cjjVrlZZojVbN4MnuG2IPUeUzoEBuA5TPE=
    # KEY_PASSWORD
    - secure: "Mte2zY0rgIa4M4bIeSKijFAFOtFy+DahRYCUgOB60cuS4b/+HMHnfmVGMqnBKitC9KVzb5fctMt2pGPK2hdlirvfkOd9ctEaEd1qSzADJjfQUKqLReOfi1N6Ln2dYqlZoDjnYpGWwTUl/uX+KtWomYW2TCZZG/uJEeh3QYkxlJQ="
    # DEVELOPER_NAME
    - secure: "CrB159u8KEwtsiCxnwvnCumiRkGgL+9aFgI2dosUvj3PtfebcVdhzRKBt+17jLapLCQEYoml8RVszLNuYpZu8y/3DhCk4ftWMumnvKOp8CIFb/4BFKMZxyuw+HlMg5oKwY4GOopnHo4mTEM51pDHMP8rfIxCjLimVeDc0uZaaj8="
  matrix:
    - CONFIG=release
  
before_install:
  - wget https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.1.4.tar.gz
  - tar -zxvf mbedtls-2.1.4.tar.gz
  - sudo mv mbedtls-mbedtls-2.1.4 /usr/local/share/mbedtls 
install:  
  - lsb_release -a
      && sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
      && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8 qtbase5-dev qt5-default
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"   
  - make -C /usr/local/share/mbedtls no_test 
script:     
  - qmake QMAKE_CXX=g++-4.8 QMAKE_C=gcc-4.8 messec.pro
  - make
  - ./src/tests/tests
