language: cpp

compiler:
  - gcc
  
before_install:
  - wget https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.1.4.tar.gz
  - tar -zxvf mbedtls-2.1.4.tar.gz
  - sudo mv mbedtls-mbedtls-2.1.4 /usr/local/share/mbedtls
  - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
  - sudo apt-get update -qq
install:
  - make -C /usr/local/share/mbedtls no_test
  - sudo apt-get install -qq qt55base; source /opt/qt55/bin/qt55-env.sh
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:                                               
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script: 
  - mkdir build
  - cd build
  - qmake ../Messec.pro
  - make
  - ./Tests
