//
// Created by Peter on 18.04.2016.
//

#ifndef MESSEC_MESSAGETYPES_H
#define MESSEC_MESSAGETYPES_H

enum MessageTypes {
	MESSAGETYPE_LOGIN,
	MESSAGETYPE_LOGOUT,
	MESSAGETYPE_GET_ONLINE_USERS,
	MESSAGETYPE_LOGIN_SUCCESS,
	MESSAGETYPE_LOGIN_FAIL,
	MESSAGETYPE_SIGNIN,
	MESSAGETYPE_SIGNIN_SUCCESS,
	MESSAGETYPE_SIGNIN_FAIL
};

#endif //MESSEC_MESSAGETYPES_H
